openapi: "3.1.0"
info:
  title: Fraudebot API Description
  version: 1.0.0
  description: |
    This API describes the Fraudebot API.
    It is used to search for scammers/organizations that have been
    reported by users.
servers:
  - url: /api
paths:
  /public/scammers/{id}:
    summary: Get a scammer by ID
    parameters:
      - name: id
        description: The ID of the scammer
        example: 1
        in: path
        required: true
        schema:
          type: string
    get:
      description: |
        Get a scammer by ID.
      responses:
        200:
          description: Returns a Scammer object
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Scammer"
        400:
          description: Returns an error message when the scammer ID is invalid
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    description: The error message
                    example: "Invalid scammer ID"
        404:
          description: Returns an error message when the scammer is not found
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    description: The error message
                    example: "Scammer not found"

components:
  schemas:
    Scammer:
      $ref: "./schemas/Scammer.yaml"
